framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
        excluded_patterns:
            - '*/assets/styles/_*.scss'
        missing_import_mode: strict
# config/packages/react.yaml
#react:
#    controllers_path: '%kernel.project_dir%/assets/dist/react/controllers/'

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
