fos_user:
  db_driver: orm
  firewall_name: login
  user_class: UserBundle\Entity\User
  service:
    mailer: fos_user.mailer.noop
  from_email:
      address: '%env(resolve:USER_ADDRESS)%'
      sender_name: '%env(resolve:SENDER_NAME)%'
